# Generated by Django 4.2.6 on 2023-10-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='taskimage',
            field=models.ImageField(blank=True, upload_to='TaskImage'),
        ),
    ]
